name: Build
on:
  push:
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

jobs:
  build:
    runs-on: windows-2025
    strategy:
      matrix:
        arch:
          - amd64
          - x86
    steps:
      - uses: actions/checkout@v5
      - name: setup MS dev commands
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: install meson and ninja
        run: pip install meson ninja
      - name: download VS headers and patch header location
        shell: bash
        run: |
          git clone https://github.com/vapoursynth/vapoursynth --depth=1 --branch R54
          cp vapoursynth/include/*.h EEDI3
          sed -i -e '/#include <V/y|<>|""|' EEDI3/shared.hpp
      - name: Meson setup
        run: meson setup builddir/ -Db_vscrt=mt -Dopencl=false
      - name: Meson compile
        run: meson compile -C builddir/ -v
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{matrix.arch}}
          path: |
            builddir/*.dll
      - name: Build release
        shell: bash
        run: |
          mv builddir/eedi3m.dll .
          7z a -bb3 -mx=9 release-${{ matrix.arch }}.7z eedi3m.dll
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: release-${{ matrix.arch }}.7z
          fail_on_unmatched_files: true
          generate_release_notes: false
          prerelease: true
