name: Build
on:
  - push
  - release
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: windows-2025
    strategy:
      matrix:
        arch:
          - amd64
          # - x86
    steps:
      - uses: actions/checkout@v5
      - name: setup MS dev commands
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
      - name: install cmake and ninja
        run: pip install cmake ninja
      - name: download VS headers and patch header location
        shell: bash
        run: |
          git clone https://github.com/vapoursynth/vapoursynth --depth=1 --branch R72
          cp vapoursynth/include/*.h EEDI3
          sed -i -e '/#include <V/y|<>|""|' EEDI3/EEDI3.h
      - name: Setup LLVM
        shell: bash
        run: |
          curl -s -o llvm-win64.exe -LJO https://github.com/llvm/llvm-project/releases/download/llvmorg-21.1.1/LLVM-21.1.1-win64.exe
          7z x -ollvm llvm-win64.exe
      - name: CMake setup
        shell: cmd
        run: cmake -S . -B builddir -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER="%cd%\llvm\bin\clang++.exe" -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
      - name: CMake compile
        run: cmake --build builddir --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{matrix.arch}}
          path: |
            builddir/*.dll
