name: Build
on:
  - push
  - release
  - pull_request
  - workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64
          - x86
    steps:
      - uses: actions/checkout@v4
      - name: setup MS dev commands
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: install meson and ninja
        run: pip install meson ninja
      - name: download VS headers and patch header location
        shell: bash
        run: |
          git clone https://github.com/vapoursynth/vapoursynth --depth=1 --branch R54
          cp vapoursynth/include/*.h EEDI3
          sed -i -e '/#include <V/y|<>|""|' EEDI3/shared.hpp
      - name: Meson setup
        run: meson setup builddir/ -Db_vscrt=mt -Dopencl=false
      - name: Meson compile
        run: meson compile -C builddir/ -v
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-${{matrix.arch}}
          path: |
            builddir/*.dll
